In [3]:
#Import required variables
import numpy as np #arrays
import pandas as pd #data processing
from sklearn.model_selection import train_test_split #split for examples and results
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score #accuracy

In [5]:
# loading dataset to a Pandas DataFrame
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [6]:
#first 5 rows
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [7]:
#last 5 rows
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [8]:
#useless step here but do it anyway - gives you some more info on any blatant fraud
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [9]:
#rows,columns
credit_card_data.shape

(284807, 31)

In [10]:
#check for any missing values
credit_card_data.isnull()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
284803,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
284804,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
284805,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
284806,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [11]:
#make life easier for yourself with easier representation
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [16]:
#Segregating Legitimate and fraudulent transcations
credit_card_data['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [17]:
# 0 --> Legitimate transactions
# 1 --> Fradulent transcations
#Dataset is unbalanced so gotta fix that - El Fix(line 24)

In [19]:
#To fix --> separate Legit and Fraud transactions
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [20]:
#get stats for each
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [21]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [22]:
#compare values for legit and fraud - notice that legit transactions are mostly in and around 0, while fraud transactions are that much more varied. This is
#easily distinguishable in this scenario but may not be in others - be vary of this.
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [24]:
# El Fix - build a sample dataset that has almost the same number of fradulent transactions to legit ones - but dont just pick out 500 legit
# ones yourself, get the computer to do it

legit_sample = legit.sample(n=500)

In [25]:
# Concatenate/Join the 2 dataframes
new_data = pd.concat([legit_sample, fraud], axis=0)

In [26]:
new_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
254378,156703.0,1.798679,-0.669975,-1.755489,0.251799,1.866671,3.998288,-1.020791,1.029632,0.733056,...,0.269008,0.644908,0.109957,0.691287,-0.077786,-0.549124,0.062257,-0.023016,82.00,0
215092,139934.0,2.105712,-0.131066,-1.656193,-0.066694,0.710380,0.151228,0.008130,-0.028385,0.327552,...,-0.313095,-0.833758,0.229161,-0.348843,-0.162339,0.210768,-0.080277,-0.073781,1.79,0
129067,78938.0,-1.268195,0.383209,0.727605,0.342739,-0.275497,-1.221347,0.288446,0.442128,-0.348990,...,-0.127411,-0.881204,0.279219,0.287834,-0.152676,0.069844,0.088226,-0.054234,99.99,0
87601,61756.0,1.357179,-0.798794,0.231036,-0.803396,-1.164343,-0.642307,-0.820209,0.126273,-0.529444,...,0.112674,-0.000226,-0.042504,-0.064202,0.344656,-0.240592,-0.024964,-0.000699,28.00,0
108395,70876.0,-0.690833,0.058808,1.773862,-0.106105,-0.328474,-0.846159,0.211587,-0.015426,-1.450997,...,-0.318467,-0.708479,0.037072,0.286099,-0.007740,-0.481292,0.094568,0.121070,45.24,0

In [27]:
new_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [28]:
new_data['Class'].value_counts()

0    500
1    492
Name: Class, dtype: int64

In [29]:
new_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,96218.556000,0.108945,0.073418,-0.002770,-0.101266,-0.036721,-0.090792,0.122045,0.027337,-0.040851,...,-0.017662,-0.047657,-0.083422,0.018473,0.026219,-0.029943,-0.019836,0.015524,0.010422,86.232660
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [30]:
# Splitting the data into Features & Targets
x = new_data.drop(columns= 'Class', axis=1)
y = new_data['Class']

In [31]:
print(x)

            Time        V1        V2        V3        V4        V5        V6  \
254378  156703.0  1.798679 -0.669975 -1.755489  0.251799  1.866671  3.998288
215092  139934.0  2.105712 -0.131066 -1.656193 -0.066694  0.710380  0.151228
129067   78938.0 -1.268195  0.383209  0.727605  0.342739 -0.275497 -1.221347
87601    61756.0  1.357179 -0.798794  0.231036 -0.803396 -1.164343 -0.642307
108395   70876.0 -0.690833  0.058808  1.773862 -0.106105 -0.328474 -0.846159
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
254378 -1.020791  1.029632  0.733056  ... -0.013864  0.269008  0.644908
215092  0.008130 -0.028385  0.327552  ... -0.141153 -0.313095 -0.833758
129067  0.288446  0.442128 -0.348990  ...  0.298095 -0.127411 -0.881204
87601  -0.820209  0.126273 -0.529444  ... -0.087958  0.112674 -0.000226
108395  0.211587 -0.015426 -1.450997  ... -0.373913 -0.318467 -0.708479
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
254378  0.109957  0.691287 -0.077786 -0.549124  0.062257 -0.023016   82.00
215092  0.229161 -0.348843 -0.162339  0.210768 -0.080277 -0.073781    1.79
129067  0.279219  0.287834 -0.152676  0.069844  0.088226 -0.054234   99.99
87601  -0.042504 -0.064202  0.344656 -0.240592 -0.024964 -0.000699   28.00
108395  0.037072  0.286099 -0.007740 -0.481292  0.094568  0.121070   45.24
...          ...       ...       ...       ...       ...       ...     ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[992 rows x 30 columns]

In [32]:
print(y)

254378    0
215092    0
129067    0
87601     0
108395    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 992, dtype: int64

In [40]:
#Split data into train and testing data
x_train, x_test,y_train, y_test = train_test_split(x, y, test_size=0.2) #stratify=y, random_state=2

In [41]:
print(x.shape,x_train.shape, x_test.shape)

(992, 30) (793, 30) (199, 30)

In [42]:
# Model Training with Logistic Regression
model = LogisticRegression()

In [44]:
#give the model the training data to get it up to speed
model.fit(x_train, y_train)

LogisticRegression()

In [46]:
#Model Evaluation

In [47]:
#Accuracy Score for train and test done separately
  #Train data
x_train_prediction = model.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction, y_train)

In [48]:
print('Accuracy on training data:', training_data_accuracy )

Accuracy on training data: 0.9419924337957125

In [49]:
#Test data
x_test_prediction = model.predict(x_test)
test_data_accuracy = accuracy_score(x_test_prediction, y_test)

In [50]:
print('Accuracy on test data:', test_data_accuracy )

Accuracy on test data: 0.9296482412060302